### ISSUE TITLE
How to post with the label "Community Calls"

### ISSUE THREAD

**Issue by ronste** [singlesourcepub/community#39]
Hi @xldrkp ,

I wanted to post an announcement for our next meeting of the "Single Source/XML-Publishing with OJS" group. But when I create a new discussion the label "Community Calls" is not available. Only "General", "Ideas", "Q&A" and "Tools".
Who can (or how can I) create a discussion with the label "Community Calls"?

Thanks,
Ronald

**Comment by xldrkp** [comment]
@ronste Thank you for this hint, "Community Call", "Announcements" and "Events" where of the GitHub category "announcement". These are closed for admins by default. I turned all three into "open ended discussion". Please check again if you can use them now.
